check:
  - thoth-precommit
  - thoth-build
release:
  - upload-pypi-sesheta
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.15.0
  build-stratergy: Source
  registry: quay.io
  registry-org: thoth-station
  registry-project: messaging
  registry-secret: thoth-station-thoth-pusher-secret
deploy:
  project-org: thoth-station
  project-name: thoth-application
  image-name: messaging
  overlay-contextpath: core/overlays/test/imagestreamtags.yaml
